# Generated by Django 4.1.7 on 2023-05-19 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_driver_bus_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='inch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incharge', to=settings.AUTH_USER_MODEL),
        ),
    ]
