# Generated by Django 4.1.7 on 2023-05-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bus_inch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='destination',
            new_name='path',
        ),
        migrations.RemoveField(
            model_name='route',
            name='fees',
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TextField(null=True)),
                ('end', models.TextField(null=True)),
                ('fees', models.IntegerField()),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.route')),
            ],
        ),
    ]
