# Generated by Django 4.1.7 on 2023-05-21 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customuser_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='end',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='route',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='start',
        ),
        migrations.RemoveField(
            model_name='route',
            name='path',
        ),
        migrations.AddField(
            model_name='destination',
            name='path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='end',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='fees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.destination'),
        ),
        migrations.AddField(
            model_name='route',
            name='start',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.route'),
        ),
    ]
