# Generated by Django 4.1.7 on 2023-05-22 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_route_end_alter_route_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='route1',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='route2',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='route3',
        ),
        migrations.AddField(
            model_name='bus',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.destination'),
        ),
    ]
