# Generated by Django 4.1.7 on 2023-05-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_bus_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='route',
        ),
    ]
