# Generated by Django 4.1.7 on 2023-05-22 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_bus_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.destination'),
        ),
    ]
