# Generated by Django 4.1.7 on 2023-05-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_destination_customuser_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='driver',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
